overrides:
  "@codemirror/state": "6.7.1"
  "@codemirror/view": "6.43.6"
  "@codemirror/language": "6.12.4"
  "@codemirror/commands": "6.10.4"
  "@codemirror/autocomplete": "6.20.3"
  "@codemirror/lint": "6.9.7"
  "@lezer/common": "1.5.2"
allowBuilds:
  "@clerk/shared": true
  "@sentry-internal/node-cpu-profiler": true
  "@sentry/cli": true
  "@sentry/node-cpu-profiler": false
  esbuild: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - "@clerk/backend@3.7.1"
  - "@clerk/nextjs@7.5.3"
  - "@clerk/react@6.10.0"
  - "@clerk/shared@4.18.0"
  - "@content-collections/core@0.15.2"
  - "@oxfmt/binding-android-arm-eabi@0.55.0"
  - "@oxfmt/binding-android-arm64@0.55.0"
  - "@oxfmt/binding-darwin-arm64@0.55.0"
  - "@oxfmt/binding-darwin-x64@0.55.0"
  - "@oxfmt/binding-freebsd-x64@0.55.0"
  - "@oxfmt/binding-linux-arm-gnueabihf@0.55.0"
  - "@oxfmt/binding-linux-arm-musleabihf@0.55.0"
  - "@oxfmt/binding-linux-arm64-gnu@0.55.0"
  - "@oxfmt/binding-linux-arm64-musl@0.55.0"
  - "@oxfmt/binding-linux-ppc64-gnu@0.55.0"
  - "@oxfmt/binding-linux-riscv64-gnu@0.55.0"
  - "@oxfmt/binding-linux-riscv64-musl@0.55.0"
  - "@oxfmt/binding-linux-s390x-gnu@0.55.0"
  - "@oxfmt/binding-linux-x64-gnu@0.55.0"
  - "@oxfmt/binding-linux-x64-musl@0.55.0"
  - "@oxfmt/binding-openharmony-arm64@0.55.0"
  - "@oxfmt/binding-win32-arm64-msvc@0.55.0"
  - "@oxfmt/binding-win32-ia32-msvc@0.55.0"
  - "@oxfmt/binding-win32-x64-msvc@0.55.0"
  - "@sentry/core@10.58.0"
  - "@sentry/node-core@10.58.0"
  - "@sentry/node@10.58.0"
  - "@sentry/opentelemetry@10.58.0"
  - "@sentry/profiling-node@10.58.0"
  - "@sentry/server-utils@10.58.0"
  - happy-dom@20.10.4
  - oxfmt@0.55.0
